var webrtc={};Object.defineProperty(Object.prototype,"forOwn",{value:function(b){for(var a in this)this.hasOwnProperty(a)&&b(this[a],a)},enumerable:!1,configurable:!1});Object.defineProperty(Object.prototype,"isNumber",{value:function(b){return!isNaN(parseFloat(b))&&isFinite(b)&&void 0===b.length},enumerable:!1,configurable:!1});Object.defineProperty(Object.prototype,"publicize",{value:function(b,a){return this[b]=a},enumerable:!1,configurable:!1});
webrtc.Class=function(b){var a={className:"webrtc.Class"};b=b||{};b.forOwn(function(b,d){a[d]=b});a.publicize("getClass",function(){return a.className});return a};Q.longStackSupport=!0;Q.stackJumpLimit=5;Q.longStackJumpLimit=20;
webrtc.Presentable=function(b){b=b||{};var a=webrtc.EventThrower(b);a.className="webrtc.Presentable";a.name="Unknown";a.id="";var c="unavailable";a.publicize("hasMedia",function(){return!1});a.publicize("canSendAudio",function(){return!0});a.publicize("canSendVideo",function(){return!0});a.publicize("getID",function(){return a.id});a.publicize("getName",function(){return a.name});a.publicize("getDisplayName",function(){return a.name});a.publicize("getPresence",function(){return c});a.publicize("setPresence",
function(b){c=b;a.fire("presence",c)});return a};webrtc.Endpoint=function(b){b=b||{};b=webrtc.Presentable(b);b.className="webrtc.Endpoint";b.mediaSessions=[];var a=mercury.getSignalingChannel();b.publicize("sendMessage",function(b,d,e){a.isOpen()&&a.send(b)});b.publicize("startMedia",function(a,b,e){});b.publicize("stopMedia",function(){});return b};
webrtc.User=function(b){b=b||{};var a=webrtc.Presentable(b);a.className="webrtc.User";var c=[],d=webrtc.UserSession({token:b.token,timeLoggedIn:b.timeLoggedIn||new Date,loggedIn:b.loggedIn});delete b.token;delete b.timeLoggedIn;delete b.loggedIn;a.publicize("getUserSession",function(){return d});a.publicize("getContactList",function(){return c});a.publicize("setOnline",function(){a.setPresence("available")});return a};
webrtc.UserSession=function(b){b=b||{};var a=webrtc.EventThrower(b);a.className="webrtc.UserSession";var c=b.token||"",d=b.loggedIn||!1;delete b.token;delete b.timeLoggedIn;delete b.loggedIn;a.publicize("getAuthToken",function(){return c});a.publicize("isLoggedIn",function(){return!!d});return a};webrtc.Contact=function(b){b=b||{};b=webrtc.Endpoint(b);b.className="webrtc.Contact";b.publicize("getMessages",function(){});return b};
webrtc.EventThrower=function(b){b=b||{};var a=webrtc.Class(b);a.className="webrtc.EventThrower";var c={};a.publicize("listen",function(a,b){c[a]=c[a]||[];"function"===typeof b&&c[a].push(b)});a.publicize("ignore",function(a,b){void 0===a?c={}:void 0===b?c[a]=[]:c[a].reverse().forEach(function(f,g){b===f&&c[a].splice(g,1)})});a.publicize("fire",function(b){if(b&&c[b]){var e=Array.prototype.slice.call(arguments,1);c[b].forEach(function(c){if("function"===typeof c)try{c.apply(a,e)}catch(g){console.log("Error in "+
a.className+"#"+b+": "+g.message),console.log(g.stack)}})}});a.publicize("getEvents",function(a){return c});return a};webrtc.IdentityProvider=function(b){b=b||{};b=webrtc.EventThrower(b);b.className="webrtc.IdentityProvider";b.publicize("login",function(a,b,d,e){});b.publicize("logout",function(){});b.publicize("isLoggedIn",function(){});return b};
webrtc.ContactList=function(b){b=b||{};var a=webrtc.EventThrower(b);a.className="webrtc.ContactList";a.length=0;var c={},d=[];a.publicize("add",function(b){if(b instanceof webrtc.Endpoint||!b.getID)throw Error("Can't add endpoint to list. Wrong type!");b.getID()in c||(a.length+=1,a.fire("new",b),c[b.getID()]=b)});a.publicize("get",function(a){return c[a]});a.publicize("remove",function(b){c.hasOwnProperty(b)&&(a.length-=1,a.fire("remove",c[b]),c[b]=void 0)});a.publicize("getSortedList",function(b){var d=
[];c.forOwn(function(a){d.push(a)});a.length=d.length;d.sort(function(a,c){var d=b||"id";return webrtc.isNumber(a[d])&&webrtc.isNumber(c[d])?a[d]-c[d]:a[d]<c[d]?-1:a[d]>c[d]?1:0});for(var g=0;g<=d.length;g+=1)d[g]=c[d[g]];return d});a.publicize("queuePresence",function(a){d.push(a)});a.publicize("processPresenceQueue",function(){for(var b=0;b<=d.length;b+=1)d[b]&&a.fire("presence",d[b]);d=[]});return a};
webrtc.MediaSession=function(b){b=b||{};var a=webrtc.EventThrower(b);a.className="webrtc.MediaSession";a.initiator||(a.initiator=!1);var c=null,d=null,e=!1,f=!1,g=[],k=[],m=mercury.getSignalingChannel(),l=[],u=b.signalInitiate,v=b.signalAccept,q=b.signalTerminate,w=b.signalReport,r=b.signalCandidate,x={video:!0,audio:!0,optional:[],mandatory:{}},n={iceServers:[{url:"turn:toto@174.129.201.5:3478",credential:"password"}]},h={startCallCount:0,startCount:0,callStarted:0,callStopped:0,roomkey:null,sessionkey:null,
lastSDPString:"",sdpsSent:[],sdpsReceived:[],candidatesSent:[],candidatesReceived:[],userAgent:navigator.userAgent,os:navigator.platform};a.publicize("start",function(){if(!a.username)throw Error("Can't use a MediaSession without username.");h.startCount+=1;console.log("calling requestMedia from start.");y()});var A=function(){h.startCallCount+=1;console.log("creating offer");c.createOffer(z,function(a){console.log("createOffer failed");console.log(a)},null)},B=function(b){console.log("User gave permission to use media.");
c.addStream(b);b=webrtc.MediaStream({stream:b,isLocal:!0});a.fire("stream:local:received",b.getURL());l.push(b);a.initiator?(a.fire("call:initiate"),A()):d?(s(d),d=null):(console.log("Can't process offer--no SDP!"),p(!0))},y=function(){var a=[];h.callStarted=(new Date).getTime();try{c=new webkitRTCPeerConnection(n,null)}catch(b){for(var e in n.iceServers)n.iceServers.hasOwnProperty(e)&&-1<n.iceServers[e].url.toLowerCase().indexOf("turn")&&a.push(e);a.sort(function(a,b){return b-a});a.each(function(a){n.iceServers.splice(a)});
c=new webkitRTCPeerConnection(n,null)}c.onaddstream=C;c.onremovestream=D;c.onicecandidate=E;c.oniceconnectionstatechange=function(a){console.log("oniceconnectionstatechange");console.log(a)};c.onstatechange=F;c.onicechange=G;d&&(s(d),d=null);try{navigator.webkitGetUserMedia(x,B,H)}catch(f){console.log("Couldn't get user media."),console.log(f)}},H=function(b){console.log("onUserMediaError");1===b.code?(console.log("Permission denied."),h.callStoppedReason="Permission denied."):(console.log(b),h.callStoppedReason=
b.code);p(!a.initiator)},D=function(a){console.log("pc event: remote stream removed")},C=function(b){console.log("received remote media");b=webrtc.MediaStream({stream:b.stream,isLocal:!1});a.fire("stream:remote:received",b.getURL());l.push(b)},F=function(a,b){console.log("iceState is "+a.currentTarget.iceState);console.log("readyState is "+a.currentTarget.readyState)},G=function(a){console.log("pc event: ice changed");console.log(a)},E=function(b){null!==b.candidate&&(a.initiator&&!e?g.push(b.candidate):
a.initiator||(h.candidatesSent.push(b.candidate),r(b.candidate)))},I=function(){for(var a=null,b=0;b<=g.length;b+=1)a=g[b],r(a);g=[];for(b=0;b<=k.length;b+=1)a=k[b],console.log("Calling processCandidate in processQueues"),console.log(a),t(a);k=[]},z=function(a){a.type="offer";console.log("setting and sending initiate");console.log(a);h.sdpsSent.push(a);c.setLocalDescription(a,function(b){u(a)},function(a){console.log("setLocalDescription failed");console.log(a)})},J=function(a){a.type="answer";console.log("setting and sending accept");
console.log(a);h.sdpsSent.push(a);c.setLocalDescription(a,function(b){v(a)},function(a){console.log("setLocalDescription failed");console.log(a)})},p=a.publicize("doHangup",function(b){console.log("hanging up");b="boolean"===typeof b?b:!0;!f&&b&&(console.log("sending bye"),q());h.callStopped=(new Date).getTime();w(h);a.fire("hangup",b);a.ignore();l.forOwn(function(a){a.stop()});c&&c.close();l=[];c=null}),s=function(b){b.type="offer";console.log("processOffer");console.log(b);try{c.setRemoteDescription(new RTCSessionDescription(b),
function(){console.log("set remote desc of offer succeeded");c.createAnswer(J,function(a){console.log("Error creating SDP answer.");h.callStoppedReason="Error creating SDP answer.";console.log(a)});a.savedOffer=null},function(c){console.log("set remote desc of offer failed");h.callStoppedReason="setLocalDescr failed at offer.";console.log(b);console.log(c);a.doHangup()})}catch(d){console.log("e: "+d.message)}};a.publicize("isCallInProgress",function(){var a=!1;if(!c)return!1;a=c.readyState in["new",
"active"];console.log("readyState is "+c.readyState+". Call is "+(a?"":"not ")+" in progress.");return a});var t=function(b){if(b)if(b.hasOwnProperty("sdpMLineIndex")&&b.candidate||(console.log("processCandidate got wrong format!"),console.log(b)),a.initiator&&!e)k.push(b),console.log("adding to queue");else{try{c.addIceCandidate(new RTCIceCandidate(b))}catch(d){console.log("err in processCandidate: "+d.message),console.log(b)}h.candidatesReceived.push(b)}};a.stopMedia=a.doHangup;a.publicize("getState",
function(){return c?c.readyState:"new"});a.publicize("isInitiator",function(){return a.initiator});a.publicize("getStreams",function(){return l});a.publicize("getLocalStreams",function(){var a=[];l.forOwn(function(b){b.isLocal()&&a.push(b)});return a});a.publicize("getRemoteStreams",function(){var a=[];l.forOwn(function(b){b.isLocal()||a.push(b)});return a});a.publicize("toggleVideo",function(){a.isCallInProgress()&&(c.localStreams[0].videoTracks[0].enabled?a.muteVideo():a.unmuteVideo())});a.publicize("toggleAudio",
function(){a.isCallInProgress()&&(c.localStreams[0].audioTracks[0].enabled?a.muteAudio():a.unmuteAudio())});a.publicize("muteVideo",function(){l.forOwn(function(a){a.muteVideo()});a.fire("video:muted")});a.publicize("unmuteVideo",function(){l.forOwn(function(a){a.unmuteVideo()});a.fire("video:unmuted")});a.publicize("muteAudio",function(){l.forOwn(function(a){a.muteAudio()});a.fire("audio:muted")});a.publicize("unmuteAudio",function(){l.forOwn(function(a){a.unmuteAudio()});a.fire("audio:unmuted")});
m.listen("received:offer",function(b){console.log("got offer");console.log(b);d=b;a.initiator?(console.log("Got initiate in precall state."),console.log(c),q()):(h.sdpsReceived.push(b),h.lastSDPString=b.sdp)});m.listen("received:answer",function(b){console.log("remote side sdp is");console.log(b);d=b;e=!0;h.sdpsReceived.push(b);h.lastSDPString=b.sdp;c.setRemoteDescription(new RTCSessionDescription(b),I,function(c){console.log("set remote desc of answer failed");h.callStoppedReason="setRemoteDescription failed at answer.";
console.log(b);a.doHangup()})});m.listen("received:candidate",t);m.listen("received:bye",function(){f=!0;p()});return a};
webrtc.MediaStream=function(b){b=b||{};var a=webrtc.EventThrower(b);a.className="webrtc.MediaStream";var c=b.stream,d=b.isLocal;a.publicize("stop",function(){c.stop()});a.publicize("muteAudio",function(){c.audioTracks[0].enabled=!1;a.fire("audio:muted")});a.publicize("muteVideo",function(){c.videoTracks[0].enabled=!1;a.fire("video:muted")});a.publicize("unmuteAudio",function(){c.audioTracks[0].enabled=!0;a.fire("audio:unmuted")});a.publicize("unmuteVideo",function(){c.videoTracks[0].enabled=!0;a.fire("video:unmuted")});
var e=a.publicize("isLocal",function(){return!!d});a.publicize("isRemote",function(){return!e()});a.publicize("getID",function(){return c.id});a.publicize("getURL",function(){return webkitURL.createObjectURL(c)});return a};
webrtc.Mercury=function(b){b=b||{};var a=webrtc.EventThrower(b);a.className="webrtc.Mercury";var c=!1,d=[];a.appSettings={signalingChannel:"XMPPSignalingChannel",identityProvider:"XMPPIdentityProvider",chatMessage:"XMPPChatMessage",signalingMessage:"XMPPSignalingMessage",presenceMessage:"XMPPPresenceMessage"};b=function(a){if(webrtc[a])return webrtc[a];if(window[a])return window[a]};a.signalingChannel=b(a.appSettings.signalingChannel)();a.identityProvider=b(a.appSettings.identityProvider)();a.chatMessage=
b(a.appSettings.chatMessage);a.signalingMessage=b(a.appSettings.signalingMessage);a.presenceMessage=b(a.appSettings.presenceMessage);a.mediaSession=b(a.appSettings.mediaSession);a.user=null;a.publicize("connect",function(){a.signalingChannel.open();c=!0});a.publicize("disconnect",function(){a.signalingChannel.close();c=!1});a.publicize("login",function(b,c){var d=a.identityProvider.login(b,c);d.then(function(b){b.setOnline();a.user=b;console.log("logged in as user");console.log(b)},function(a){console.log(a.message)}).done();
return d});a.publicize("logout",function(b){var c=[];d.forEach(function(d,k){if(!b||d.userAccount in b)a.identityProvider.logout(d.userAccount,d.token),d.loggedIn=!1,c.push(k)});c.reverse().forEach(function(a){d.remove(a)});0===d.length&&(a.user=null)});a.publicize("isConnected",function(){return!!c});a.publicize("isLoggedIn",function(){var a=!1;d.forEach(function(b){a=a||b.loggedIn});return!!a});a.publicize("getUserSessions",function(){return d});a.publicize("getDefaultMediaSettings",function(){return a.mediaSettings});
a.publicize("setDefaultMediaSettings",function(b){b=b||{};b.constraints&&(a.mediaSettings.constraints=b.constraints);b.servers&&(a.mediaSettings.servers=b.servers)});a.publicize("getSignalingChannel",function(){return a.signalingChannel});return a};
webrtc.SignalingChannel=function(b){b=b||{};b=webrtc.EventThrower(b);b.className="webrtc.SignalingChannel";var a="new";b.publicize("open",function(){a="open"});b.publicize("close",function(){a="closed"});b.publicize("getState",function(){return a});b.publicize("isOpen",function(){return"open"===a});b.publicize("send",function(a){});return b};
webrtc.Message=function(b){b=b||{};b=webrtc.Class(b);b.className="webrtc.Message";b.publicize("parse",function(a){});b.publicize("getPayload",function(){});b.publicize("getText",function(){});return b};
webrtc.XMPPSignalingChannel=function(b){b=b||{};var a=webrtc.SignalingChannel(b);a.className="webrtc.XMPPSignalingChannel";var c="new",d=null;a.publicize("open",function(){d=new Strophe.Connection("http://mercury.digiumlabs.com:5280/http-bind/");c="open"});a.publicize("close",function(){d.disconnect();c="closed"});a.publicize("getState",function(){return c});a.publicize("isOpen",function(){return"open"===c});a.publicize("sendPresence",function(a){var b=null;switch(a){case "":case null:case void 0:case !1:case "available":b=
$pres();break;case "unavailable":b=$pres({type:"unavailable"});break;case "dnd":case "away":case "xa":b=$pres().c("show",{},a);break;default:throw Error("Can't send invalid presence "+a+"!");}d.send(b.tree())});a.publicize("requestRoster",function(a){if(!a)throw Error("Can't request roster without JID.");a=$iq({from:a,type:"get",id:"roster_1"}).c("query",{xmlns:Strophe.NS.ROSTER}).tree();d.send(a)});a.publicize("sendMessage",function(a){var b=a.getXMPP();d.send(b.tree());a.getRecipient().fire("message:sent",
a)});a.publicize("send",function(a,b){var c="";b?a?a===d.jid?console.log("Can't send, recipient is me!"):(console.log("sending a "+b.type),c=$msg({to:a,from:d.jid,type:"signaling"}).c("signaling",{xmlns:"mercury:signaling"},escape(JSON.stringify(b))).tree(),console.log(c),d.send(c)):console.log("Can't send, recipient is "+a):console.log("Can't send, no message.")});a.publicize("sendCandidate",function(a,b){var c="";if(!d.jid||!a)throw Error("Can't send without sender and recipient.`");c=$msg({to:a,
from:d.jid,type:"signaling"}).c("signaling",{xmlns:"mercury:signaling",type:"candidate"},escape(JSON.stringify(b))).tree();console.log(c);d.send(c)});a.publicize("sendSDP",function(a,b){var c="";if(!d.jid||!a)throw Error("Can't send without sender and recipient.`");c=$msg({to:a,from:d.jid,type:"signaling"}).c("signaling",{xmlns:"mercury:signaling",type:b.type},escape(JSON.stringify(b))).tree();console.log(c);d.send(c)});a.publicize("sendBye",function(a,b){var c="";if(!d.jid||!a)throw Error("Can't send without sender and recipient.`");
c=$msg({to:a,from:d.jid,type:"signaling"}).c("signaling",{xmlns:"mercury:signaling",type:"bye"},escape(JSON.stringify({type:"bye",reason:b}))).tree();console.log(c);d.send(c)});a.publicize("parseText",function(a){var b={},c=null,c=a.getElementsByTagName("signaling");if(0===c.length)return null;c=c[0];b.value=unescape(Strophe.getText(c));b.from=a.getAttribute("from");b.to=a.getAttribute("to");b.type=c.getAttribute("type");try{b.value=JSON.parse(b.value)}catch(d){}return b});a.publicize("routeSignal",
function(b){mercury.user.getMediaSessionByContact(b.sender);b=b.getPayload();switch(b.type){case "offer":case "answer":case "candidate":case "bye":a.fire("received:"+b.type,b.value);break;case "error":console.log("Received an error");console.log(b);break;default:console.log("Don't know what to do with msg of unknown type "+b.type)}});a.publicize("addHandler",function(a,b){d.addHandler(b,null,a,null,null,null)});a.publicize("authenticate",function(a,b,c){d.connect(a,b,c)});return a};
webrtc.XMPPIdentityProvider=function(b){b=b||{};b=webrtc.IdentityProvider(b);b.className="webrtc.XMPPIdentityProvider";var a=null,c=!1;b.publicize("login",function(b,c){var f=null;null===a&&(a=mercury.getSignalingChannel());a.isOpen()||a.open();f=Q.defer();a.authenticate(b,c,function(a){var c=null;a===Strophe.Status.CONNECTED?(console.log("Strophe is connected."),c=webrtc.XMPPUser({jid:b,loggedIn:!0}),f.resolve(c)):a===Strophe.Status.ERROR?f.reject(Error("Unknown error.")):a===Strophe.Status.AUTHFAIL?
f.reject(Error("Authentication failure.")):a===Strophe.Status.CONNFAIL?f.reject(Error("Couldn't connect.")):a===Strophe.Status.DISCONNECTED?f.reject(Error("Got disconnected.")):a!==Strophe.Status.AUTHENTICATING&&a!==Strophe.Status.ATTACHED&&a!==Strophe.Status.CONNECTING&&a!==Strophe.Status.DISCONNECTING&&console.log("unknown strophe connection status. "+a)});return f.promise});b.publicize("logout",function(){a.listen("closed",function(){c=!1});a.close()});b.publicize("isLoggedIn",function(){return!!c});
return b};
webrtc.XMPPPresentable=function(b){b=b||{};var a=webrtc.Presentable(b);a.className="webrtc.XMPPPresentable";a.domain=null;a.username=null;a.emailFormat=null;a.resourceFormat=null;a.idstring=null;var c=[];b=function(){var b=[],e=[];if(!a.jid)throw Error("Can't use an XMPPPresentable without a JID.");b=a.jid.split("/");b[1]&&c.push({resource:b[1],presence:"unavailable",show:""});e=b[0].split("@");a.emailFormat=b[0];a.username=e[0];a.name=e[0];a.domain=e[1];if(!a.username||!a.domain||!a.emailFormat)throw Error("Can't create an XMPPPresentable. "+a.jid+
" is wrong format!");a.idstring=a.emailFormat.replace("@",".")};a.publicize("getID",function(){return a.emailFormat});a.publicize("getEmailFormat",function(){return a.emailFormat});a.publicize("getResourceFormat",function(){return a.jid});a.publicize("getIDString",function(){return a.idstring});a.publicize("getDisplayName",function(){return a.name||a.username||a.jid||a.emailFormat});a.publicize("getUsername",function(){return a.username});a.publicize("matchesJID",function(b){var c=[],f=null;if(!b||
!a.jid)return!1;c=b.split("/");f=RegExp("^"+a.username+"\\@"+a.domain+"\\/?\\w*$","i");return f.test(c[0])});a.publicize("getStatus",function(){return"unavailable"});a.jid&&b();return a};webrtc.XMPPEndpoint=function(b){b=b||{};var a=webrtc.XMPPPresentable(b);a.className="webrtc.XMPPEndpoint";var c=mercury.getSignalingChannel();a.publicize("sendMessage",function(b){c.sendMessage(webrtc.XMPPChatMessage({recipient:a,sender:mercury.user.getResourceFormat(),payload:b}))});return a};
webrtc.XMPPContact=function(b){b=b||{};var a=webrtc.XMPPEndpoint(b);a.className="webrtc.XMPPContact";var c="unavailable",d={};a.publicize("setPresence",function(a,b){a=a||"available";d.hasOwnProperty(b)||(d[b]={resourceID:b,presence:a});d[b].presence=a;e()});var e=function(){d.forOwn(function(a){switch(a.presence){case "chat":c=a.presence;break;case "available":c in["chat"]||(c=a.presence);break;case "away":c in["chat","available"]||(c=a.presence);break;case "dnd":c in["chat","available","away"]||
(c=a.presence);break;case "xa":c in["chat","available","away","dnd"]||(c=a.presence)}});c||(c="unavailable");a.fire("presence",c)};return a};
webrtc.XMPPUser=function(b){b=b||{};var a=webrtc.XMPPPresentable(b);a.className="webrtc.XMPPUser";var c=[],d=new webrtc.ContactList,e=mercury.getSignalingChannel(),f=new webrtc.UserSession({token:b.token,timeLoggedIn:b.timeLoggedIn,loggedIn:b.loggedIn});a.listen("presence",function(a){e&&e.isOpen()?(console.log("sending my presence update "+a),e.sendPresence(a)):console.log("Can't send my presence: no signaling channel.")});d.listen("new",function(b){a.fire("contact:new",b)});d.listen("presence",
function(b){try{var c=b.getPayload();if("error"!==c.presence){var d=b.sender.split("/"),e=d[0],f=d[1],g=this.get(e);e===a.jid&&f!==a.resource?this.remoteUserSessions[f]={jid:a.jid,resource:f,presence:c.presence}:g&&g.setPresence(c.presence,f)}}catch(k){console.log(k.message),console.log(k.stack),console.log(b)}});a.publicize("requestContacts",function(){var b=Q.defer();if(!f.isLoggedIn())return b.reject(Error("Can't request contacts unless logged in.")),b.promise;b.promise.then(function(a){a.processPresenceQueue()});
e.addHandler("iq",function(a){console.log(a);a=$j(a).find("item");if(0===a.length)return b.reject(Error("No items in the roster.")),!0;a.each(function(){var a=$j(this).attr("subscription"),b=$j(this).attr("jid"),c=$j(this).attr("name"),e=null;if(!a||"to"===a||"both"===a){try{e=new webrtc.XMPPContact({jid:b,name:c,subscription:a})}catch(m){console.log("Couldn't create contact: "+m.message);return}d.add(e)}});b.resolve(d);return!0});e.requestRoster(a.getResourceFormat());return b.promise});a.publicize("getUserSession",
function(){return f});var g=a.publicize("startMedia",function(b,d){var f=webrtc.MediaSession({username:a.username,remoteEndpoint:b,initiator:d,signalInitiate:function(a){a.type="offer";e.sendSDP(b,a)},signalAccept:function(a){a.type="answer";e.sendSDP(b,a)},signalCandidate:function(a){a&&e.sendCandidate(b,a)},signalTerminate:function(){console.log("signalTerminate");e.sendBye(b)},signalReport:function(a){console.log("Not sending report");console.log(a)}});c.push(f);f.start();a.fire("media:started",
f,b);a.listen("hangup",function(a){k(b)});return f});a.publicize("getActiveMediaSession",function(){var a=null;c.forEach(function(b){b.isActive()&&(a=b)});return a});a.publicize("getMediaSessionByContact",function(a){var b=null;c.forEach(function(c){c.remoteEndpoint===a&&(b=c)});null===b&&(b=g(a,!1));return b});var k=a.publicize("stopMedia",function(a){var b=null;c.forEach(function(c,d){c.remoteEndpoint===a&&(b=d)});null===b?console.log("Couldn't find mediaSession in stopMedia"):(c[b].doHangup(),
c.splice(b))});a.publicize("setOnline",function(){e.addHandler("presence",function(b){console.log(b);b=mercury.presenceMessage({rawMessage:b,sender:b.getAttribute("from"),recipient:a});0===d.length?d.queuePresence(b):d.fire("presence",b);return!0});e.addHandler("message",function(b){console.log(b);var c=b.getAttribute("from"),e=b.getAttribute("type");if(-1===["chat","signaling","groupchat"].indexOf(e))return console.log("wrong type "+e),!0;c=c.split("/");c=d.get(c[0]);if(!c)return console.log("no contact"),
!0;b={rawMessage:b,recipient:a,sender:c.getResourceFormat()};"signaling"===e?c.fire("signaling:received",mercury.signalingMessage(b)):c.fire("message:received",mercury.chatMessage(b));return!0});a.setPresence("available")});return a};
webrtc.XMPPChatMessage=function(b){b=b||{};var a=webrtc.Message(b);a.className="webrtc.XMPPChatMessage";var c=b.rawMessage,d=b.payload,e=b.sender,f=b.recipient;b=a.publicize("parse",function(a){a&&(c=a);try{d=Strophe.getText(c.getElementsByTagName("body")[0])}catch(b){console.log("Not an XMPP text message!")}});a.publicize("getXMPP",function(){return $msg({to:f.getEmailFormat(),from:e,type:"chat"}).c("body").t(d)});var g=a.publicize("getPayload",function(){return d});a.publicize("getText",g);a.publicize("getRecipient",
function(){return f});c&&b();return a};webrtc.XMPPSignalingMessage=function(b){b=b||{};var a=webrtc.Message(b);a.className="webrtc.XMPPSignalingMessage";var c=b.rawMessage,d=null,e=b.recipient;b=a.publicize("parse",function(){d=mercury.getSignalingChannel().parseText(c)});a.publicize("getText",function(){return d.type});a.publicize("getPayload",function(){return d});a.publicize("getRecipient",function(){return e});c&&b();return a};
webrtc.XMPPPresenceMessage=function(b){b=b||{};var a=webrtc.Message(b);a.className="webrtc.XMPPPresenceMessage";var c=b.rawMessage,d={},e=b.sender,f=b.recipient;b=a.publicize("parse",function(a){var b="",b=[];a&&(c=a);d.presence=c.getAttribute("type")||"available";b=$j(c).find("show");0!==b.length&&(b=Strophe.getText(b[0]))&&(d.presence=b)});a.publicize("getXMPP",function(){if(!d)throw Error("No message payload.");return $msg({to:f.getEmailFormat(),from:e,type:"chat"}).c("body").t(d)});a.publicize("getText",
function(){if(!d)throw Error("No message payload.");return d.presence});a.publicize("getPayload",function(){return d});a.publicize("getRecipient",function(){return f});c&&b();return a};