#!/bin/bash

JSHINT_OUTPUT=`jshint brightstream.js brightstream/*.js`
if [ "$JSHINT_OUTPUT" != "" ]; then
    echo There were some errors.
	echo JSHINT_OUTPUT is $JSHINT_OUTPUT
	exit 1
fi

# library minification
grunt combine
grunt dist

# Upgrade the pre-commit hook.
if [ -d '.git/hooks/pre-commit' ]; then
    cp githooks/pre-commit .git/hooks/pre-commit
fi
if [ -d '../../.git/modules/javascript/transporter/hooks/pre-commit' ]; then
    cp githooks/pre-commit ../../.git/modules/javascript/transporter/hooks/pre-commit
fi
