#!/bin/bash

JSHINT_OUTPUT=`jshint brightstream.js brightstream/*.js`
if [ "$JSHINT_OUTPUT" != "" ]; then
    echo There were some errors.
	echo JSHINT_OUTPUT is $JSHINT_OUTPUT
	exit 1
fi
./minimize.sh
