#!/bin/bash

JSHINT_OUTPUT=`jshint brightstream.js brightstream/*.js`
if [ "$JSHINT_OUTPUT" != "" ]; then
    echo There were some errors.
	echo JSHINT_OUTPUT is $JSHINT_OUTPUT
	exit 1
fi

# library minification
grunt combine
grunt dist

# Upgrade the pre-commit hook.
cp githooks/pre-commit .git/hooks/pre-commit  || cp githooks/pre-commit ../../.git/modules/javascript/transporter/hooks/pre-commit
